development:
    app_name        :   ImageViewer
    upload_enable   :   false
    http_port       :   8082
    entry_point     :   imageviewer
    default_paging  :   50
    image_root_dir  :   public/images
    bootstrap_dir   :   bootstrap-3.3.2-dist
    jcrop_dir       :   Jcrop
    jquery_path     :   public/js/jquery-2.1.3.min.js
    enable_module   :
        listview: True
        compare: False
        annotation: True
    enable_annotation_modules:
        label: True
        region: True
    db_name:    imageviewer
    label_annotation_conf_dir:  public/task/annotation/label
    label_annotation_collection_name_prefix: label_
    region_annotation:
        conf_dir: public/task/annotation/region
        collection_name_prefix: region_
